---

- hosts: "all"
  become: true
  become_user: root
  vars_files:
    - 'vars/{{ ansible_os_family|lower }}.yml'

  tasks:

  - name: "Installing Additional Packages If Necessary"
    package:
      name: '{{ packages }}'
      state: present
    vars:
      packages:
      - '{{ pigz }}'
      - '{{ socat }}'
      - '{{ mariabackup }}'

- hosts: "master"
  become: true
  become_user: root

  tasks:

  - name: "Backup, Compress & Stream To Target"
    shell: /usr/bin/mariabackup --backup --target-dir=/tmp --stream=xbstream --parallel={{ ansible_processor_vcpus }} | pigz -c | socat - TCP-LISTEN:4444,reuseaddr
    async: 86400
    poll: 0
    register: socat_sleeper

- hosts: "slave"
  become: true
  become_user: root

  tasks:

  - name: "Stopping MariaDB on Slave"
    systemd:
      name: mariadb
      state: stopped

  - name: "Emptying /var/lib/mysql/"
    shell: rm -rf /var/lib/mysql/*
    args:
      warn: false

  - name: "Emptying /var/log/mysql/"
    shell: rm -rf /var/log/mysql/*
    args:
      warn: false

  - name: "Receiving Stream From Master"
    shell: socat -u TCP:{{ socat_source }}:4444 STDOUT | pigz -dc | mbstream -x
    args:
      chdir: /var/lib/mysql/

  - name: "Preparing Backup"
    shell: /usr/bin/mariabackup --use-memory=1G --prepare --target-dir=/var/lib/mysql/

  - name: "Changing Ownership Of Data Dir"
    file:
      path: /var/lib/mysql
      recurse: yes
      owner: mysql
      group: mysql

  - name: "Removing Empty ib_logfile0"
    file:
      path: /var/lib/mysql/ib_logfile0
      state: absent

  - name: "Starting MariaDB On Slave"
    systemd:
      name: mariadb
      state: started

  - name: "Setting Up Replication"
    mysql_replication:
      mode: changemaster
      master_host: '{{ master_server }}'
      master_port: 3306
      master_user: '{{ repli_user }}'
      master_password: '{{ repli_pass }}'

  - name: "Getting GTID Information"
    shell: awk '{print $3}' /var/lib/mysql/xtrabackup_binlog_info
    register: gtid_info

  - name: "Setting Slave GTID Position"
    shell: mysql -e "SET GLOBAL gtid_slave_pos = '{{ gtid_info.stdout }}'; CHANGE MASTER TO master_use_gtid=slave_pos";

  - name: "Starting Replication"
    mysql_replication:
      mode: startslave
