---

- hosts: "all"
  become: true
  become_user: root

  tasks:

  - name: "Installing Additional Packages If Necessary"
    apt:
      name={{ item }}
      state=present
    with_items:
      - liblz4-tool
      - socat
      - percona-xtrabackup-24
      - mariadb-backup

- hosts: "master"
  become: true
  become_user: root

  tasks:

  - name: "Backup, Compress & Stream To Target"
    shell: /usr/bin/mariabackup --backup --target-dir=/tmp --stream=xbstream --parallel=2 | lz4 | socat - TCP-LISTEN:4444,reuseaddr
    async: 86400
    poll: 0
    register: socat_sleeper

- hosts: "slave"
  become: true
  become_user: root

  tasks:

  - name: "Stopping MariaDB"
    systemd:
      name: mariadb
      state: stopped

  - name: "Emptying /var/lib/mysql/"
    shell: rm -rf /var/lib/mysql/*
    args:
      warn: false

  - name: "Emptying /var/log/mysql/"
    shell: rm -rf /var/log/mysql/*
    args:
      warn: false

  - name: "Receiving File From Master"
    shell: socat -u TCP:{{ socat_source }}:4444 STDOUT > snapshot.xb.lz4
    args:
      chdir: /var/lib/mysql/

  - name: "Unarchiving Backup File"
    shell: lz4cat snapshot.xb.lz4 | mbstream -x
    args:
      chdir: /var/lib/mysql/

  - name: "Removing Archive File"
    file:
      path: /var/lib/mysql/snapshot.xb.lz4
      state: absent

  - name: "Getting Master GTID Position"
    shell: awk '{print $3}' /var/lib/mysql/xtrabackup_binlog_info
    register: master_gtid

  - name: "Setting Binlog Facts"
    set_fact:
      gtid_slave_pos: "{{ master_gtid.stdout }}"

  - name: "Preparing Backup"
    shell: /usr/bin/xtrabackup --prepare --target-dir=/var/lib/mysql/

  - name: "Changing Ownership Of Data Dir"
    file:
      path: /var/lib/mysql
      recurse: yes
      owner: mysql
      group: mysql

  - name: "Starting MariaDB"
    systemd:
      name: mariadb
      state: started

  - name: "Setting Up Replication"
    mysql_replication:
      mode: changemaster
      master_host: "{{ master_server }}"
      master_port: 3306
      master_user: "{{ repli_user }}"
      master_password: "{{ repli_pass }}"

  - name: "Setting Slave GTID Position"
    shell: mysql -e "SET GLOBAL gtid_slave_pos = '{{ gtid_slave_pos  }}'; CHANGE MASTER TO master_use_gtid=slave_pos";

  - name: "Starting Replication"
    mysql_replication:
      mode: startslave
